/**
 * Presents a confirmation interface for exporting an EarnProof artifact.
 *
 * ArtifactExport intentionally separates artifact creation from artifact
 * delivery. The supplied `ArtifactExportPlan` contains the serialized body,
 * approved filename, MIME type, included fields, and disclosure warnings.
 *
 * The component supports:
 * - copying the serialized artifact to the clipboard;
 * - downloading the artifact through the export utility;
 * - displaying disclosure warnings before export;
 * - accessible dialog semantics;
 * - polite status announcements;
 * - user-visible error handling without exposing credential contents.
 *
 * @param props - Artifact export configuration.
 * @param props.plan - Export plan generated by the credential export helpers.
 *   When null, no export controls are rendered.
 * @param props.title - Accessible label for the button that opens the export
 *   confirmation interface.
 *
 * @example
 * ```tsx
 * const plan = buildCredentialExport({
 *   credential,
 *   proof,
 * });
 *
 * return (
 *   <ArtifactExport
 *     plan={plan}
 *     title="Export credential"
 *   />
 * );
 * ```
 *
 * @accessibility
 * The confirmation interface uses `role="dialog"`, `aria-modal`,
 * `aria-labelledby`, an `aria-live` status region, and `role="alert"` for
 * failures. All actions are native buttons and therefore keyboard accessible.
 *
 * @security
 * The component never constructs export filenames itself and delegates
 * download validation to `downloadTextFile`. Error messages intentionally
 * avoid rendering credential or wallet data.
 *
 * @edgeCases
 * A null export plan renders nothing. Clipboard and download failures are
 * converted into actionable user-facing errors.
 */
export function ArtifactExport({
